---
- name: wordpress install
  hosts: web
  become: yes

  tasks:   
    - name: install repo epel-release,remi-release-7
      yum:
        name: "{{ repositorys }}"
        state: present
      vars:
        repositorys:
          - "epel-release"
          - "http://rpms.famillecollet.com/enterprise/remi-release-7.rpm"
    
    - name: apache install
      yum:
        name: httpd
        state: latest
        enablerepo: epel

    - name: wordpress pkg install
      get_url:
        url: http://wordpress.org/latest.tar.gz
        dest: /tmp/latest.tar.gz

    - name: check install wprdpress pkg
      stat: 
        path: "/tmp/latest.tar.gz"
      register: pkg_result  

    - name: unarchive wordpress pkg
      unarchive:
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes
      when: pkg_result.stat.exists == true  

    - name: check wordpress directory 
      stat:
        path: "/var/www/html/wordpress"
      register: result

    - name:
      file: 
        path: /var/www/html/wordpress
        owner: "apache"
        group: "apache"
        mode: "755"
        recurse: yes
      when: result.stat.exists == true

    - name: check remi.repo
      stat:
        path: "/etc/yum.repos.d/remi.repo"
      register: repo_result

    - name: install php version "{{ version }}"
      yum:
        name: "{{ packages }}"
        state: latest
        enablerepo: remi-php{{ version }}
      when: repo_result.stat.exists == true
      vars:
        version:
          - 74
        packages:
          - php 
          - php-cli 
          - php-pdo 
          - php-fpm 
          - php-json 
          - php-mysqlnd

    - name: apache restart
      service:
        name: httpd
        state: restarted
        enabled: yes

